# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b270d9389f02716c463b23fbb92a07119f9ae8577b67edfe32715fa2efc5e607e5987f8a3a91b660588119bbc65a33d1d7381b0bc83b5eeb9b71a566af0de6de

test:
  secret_key_base: 46b62e8ea45a690870d015699ea4b8c3e7e1f777b39963e6a1a774d2df826a3d1930ba7e6cc6d06d8223c640782d08d82fe0649c94b2fcf60f02b1bc959748e8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
